### ISSUE TITLE
Related field seriaizes as an integer even if the primary key is a string

### ISSUE THREAD

**Issue by emacsen** [klen/marshmallow-peewee#120]
From fields.py

```
    def _deserialize(self, value, attr, data, **kwargs):
        if isinstance(value, str):
            return int(value)

        return super(Related, self)._deserialize(value, attr, data)
```

But in my models.py, my primary key is a StringField, so this breaks.

A fix would be to either look at the field type of the other ModelSchema it's "Related" to, or at least let the user pass in a parameter to serialize it to.

**Comment by klen** [comment]
Thank you for the feedback. Fixed in version > 3.1
