### ISSUE TITLE
Support for Marshmallow version 3.0.0

### ISSUE THREAD

**Issue by den4uk** [klen/marshmallow-peewee#80]
Currently `marshmallow-peewee` supports `marshmallow<=3.0.0rc5`, but not higher release candidates.

As a consumer, I would like this library to support the latest release of Marshmallow once a stable version is published.
The latest release now is version 3.0.0rc9.

Here is a pending PR to address what was removed from Marshmallow, in order to support version 2 and 3:
https://github.com/klen/marshmallow-peewee/pull/78

**Comment by artemnesterenko** [comment]
Marshmallow 3 is out

**Comment by den4uk** [comment]
PR updated with MA 3.0.0, all passes.

**Comment by klen** [comment]
done
