### ISSUE TITLE
ForeignKey field with `_id` suffix

### ISSUE THREAD

**Issue by Behoston** [klen/marshmallow-peewee#86]
Hi. I think marshmallow-peewee may provide option that serialize (and deserialize) ForeignKey fields with `_id` suffix. 

On API we have:
```json
{
  "id": "1",
  "title": "The Chronicles of Narnia",
  "author": "1"
}
```

For me is not clear if "1" is author pseudonym or id of another model named author. 

```json
{
  "id": 1,
  "title": "The Chronicles of Narnia",
  "author_id": 1
}
```

I'll be trying to hack on my own, but I'm not sure if you want this feature as part of package.

**Comment by den4uk** [comment]
I like the idea, which would make looking at the dumped data a lot more explicit, and in-line with how other ORM's work. Just to keep in mind, that is it likely to break backwards capability for existing datasets.

This would work in a major version change for the library, perhaps the maintainer could set a milestone, where such wish-list suggestions could be accumulated and applied?

**Comment by klen** [comment]
a "little bit" late, but I've add an option for this: `Meta.id_keys`
