### ISSUE TITLE
[question] String type for AutoField

### ISSUE THREAD

**Issue by ak4nv** [klen/marshmallow-peewee#97]
What the point of using marshmallow `String` type for peewee `AutoField` instead of `Integer`?
Is it bug or feature?
https://github.com/klen/marshmallow-peewee/blob/595867d16cd13a28e529a499e963b98761eea2ea/marshmallow_peewee/convert.py#L15

**Comment by klen** [comment]
Thank you for the feedback. It's are not used anymore.

**Comment by ak4nv** [comment]
Два года ждал :rofl:
